// <auto-generated />
using System;
using AppTechnoSoft.Interns.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppTechnoSoft.Interns.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240528160414_StudentNullables")]
    partial class StudentNullables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d5d1c1bc-b50f-4835-998d-04fd98833154",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2010785-619f-4edb-a5b4-fa6db2850812",
                            Email = "rawal.bishnu@live.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "RAWAL.BISHNU@LIVE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED5lBz8Dgt3AdLyMC0N0uzUWPxB5vN1AKeF/HXKTIgHE5sOACP0gbRMj+2x2RXDOYA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c11a13df-e734-41c2-9ef8-5d52026d4851",
                            TwoFactorEnabled = false,
                            UserName = "rawal.bishnu@live.com"
                        });
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("PunchIn")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("PunchOut")
                        .HasColumnType("time");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkLog")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.BatchBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Allocation")
                        .HasColumnType("real");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("BatchBudgets");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClassStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DurationHours")
                        .HasColumnType("real");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WidgetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("WidgetId");

                    b.ToTable("ClassSchedules");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Bhadrapur, Jhapa",
                            Name = "Mechi Multiple Campus"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Dhankuta",
                            Name = "Dhankuta Multiple Campus"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Dharan",
                            Name = "Central Campus of Technology"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Biratnagar",
                            Name = "Mahendra Morang Adarsha Multiple Campus"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Rajbiraj",
                            Name = "Mahendra Bindeshwori Multiple Campus"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Siraha",
                            Name = "Surya Narayan Satya Na. Mo. Yadav Campus"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Janakpur",
                            Name = "Ramsorup Ramsagar Multiple Campus"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Birgunj",
                            Name = "Thakur Ram Multiple Campus"
                        },
                        new
                        {
                            Id = 9,
                            Location = "Bharatpur",
                            Name = "Birendra Multiple Campus"
                        },
                        new
                        {
                            Id = 10,
                            Location = "Pokhara",
                            Name = "Prithivi Narayan Multiple Campus"
                        },
                        new
                        {
                            Id = 11,
                            Location = "Mahendranagar",
                            Name = "SidhaNath Science Campus"
                        },
                        new
                        {
                            Id = 12,
                            Location = "Nepalgunj",
                            Name = "Mahendra Multiple Campus"
                        },
                        new
                        {
                            Id = 13,
                            Location = "Butwal",
                            Name = "Butwal Multiple Campus"
                        },
                        new
                        {
                            Id = 14,
                            Location = "Palpa",
                            Name = "Tribhuvan Multiple Campus"
                        },
                        new
                        {
                            Id = 15,
                            Location = "Ghantaghar",
                            Name = "Tri-Chandra Multiple Campus"
                        },
                        new
                        {
                            Id = 16,
                            Location = "Lainchour",
                            Name = "Amrit Science Campus"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Patan",
                            Name = "Patan Multiple Campus"
                        },
                        new
                        {
                            Id = 18,
                            Location = "Bhaktapur",
                            Name = "Bhaktapur Multiple Campus"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Bagbazar",
                            Name = "Padma Kanya Multiple Campus"
                        },
                        new
                        {
                            Id = 20,
                            Location = "Ghorahi, Dang",
                            Name = "Mahendra Multiple Campus"
                        },
                        new
                        {
                            Id = 21,
                            Location = "Baglung",
                            Name = "Dhaulagiri Campus"
                        },
                        new
                        {
                            Id = 22,
                            Location = "Gorkha",
                            Name = "Gorkha Campus"
                        },
                        new
                        {
                            Id = 23,
                            Location = "Bhairahawa",
                            Name = "Bhairahawa Multiple Campus"
                        },
                        new
                        {
                            Id = 24,
                            Location = "Biratnagar",
                            Name = "Degree Campus"
                        });
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.FinAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<float>("FeeAmount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PaidAmount")
                        .HasColumnType("real");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("FinAccounts");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Publish")
                        .HasColumnType("bit");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoardUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ApplicantType")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DbExperience")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FormSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneralProgramming")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TechProgramId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTrack")
                        .HasColumnType("int");

                    b.Property<int>("WebExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CollegeId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TechProgramId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.StudentAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Evaluation")
                        .HasColumnType("tinyint");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolutionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentAssignments");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.TechProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Affliation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Affliation = "TU",
                            Name = "BCA"
                        },
                        new
                        {
                            Id = 2,
                            Affliation = "PU",
                            Name = "BCA"
                        },
                        new
                        {
                            Id = 3,
                            Affliation = "TU",
                            Name = "BIT"
                        },
                        new
                        {
                            Id = 4,
                            Affliation = "PU",
                            Name = "BIT"
                        },
                        new
                        {
                            Id = 5,
                            Affliation = "TU",
                            Name = "BIM"
                        },
                        new
                        {
                            Id = 6,
                            Affliation = "TU",
                            Name = "BScIT"
                        },
                        new
                        {
                            Id = 7,
                            Affliation = "PU",
                            Name = "BScIT"
                        });
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.TraineeTimeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TraineeTimelines");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Widget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Widgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1903),
                            CreatedBy = "Seed",
                            Description = "An display item in home page",
                            HtmlContent = "Welcome to AppTechnoSoft! An initiative for students and freshers.",
                            Title = "CarouselItem"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1923),
                            CreatedBy = "Seed",
                            Description = "An display item in home page",
                            HtmlContent = "Bridging the gap between academia and industry!",
                            Title = "CarouselItem"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1927),
                            CreatedBy = "Seed",
                            Description = "An display item in home page",
                            HtmlContent = "We guide you on software R&D and SDLC to kickstart your career!",
                            Title = "CarouselItem"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1930),
                            CreatedBy = "Seed",
                            Description = "An display item in home page",
                            HtmlContent = "Replacement Opportunities!",
                            Title = "CarouselItem"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1932),
                            CreatedBy = "Seed",
                            Description = "An display item in home page",
                            HtmlContent = "From basics to professional touches!",
                            Title = "CarouselItem"
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1935),
                            CreatedBy = "Seed",
                            Description = "GIT and GitHub Essentials",
                            HtmlContent = "todo",
                            Title = "Module"
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2024, 5, 28, 21, 49, 11, 347, DateTimeKind.Local).AddTicks(1937),
                            CreatedBy = "Seed",
                            Description = "Training + Internship Combo",
                            HtmlContent = "todo",
                            Title = "HomeIntro"
                        });
                });

            modelBuilder.Entity("InstructorTag", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("InstructorTag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6d092d67-be01-49e9-a8e1-f2a8977ae592",
                            ConcurrencyStamp = "6d092d67-be01-49e9-a8e1-f2a8977ae592",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "c9998673-0fd7-4ead-ab18-b0ea8a22999c",
                            ConcurrencyStamp = "c9998673-0fd7-4ead-ab18-b0ea8a22999c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "8453e6fc-6c42-470e-a602-f3263b60ac30",
                            ConcurrencyStamp = "8453e6fc-6c42-470e-a602-f3263b60ac30",
                            Name = "Trainee",
                            NormalizedName = "TRAINEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d5d1c1bc-b50f-4835-998d-04fd98833154",
                            RoleId = "6d092d67-be01-49e9-a8e1-f2a8977ae592"
                        },
                        new
                        {
                            UserId = "d5d1c1bc-b50f-4835-998d-04fd98833154",
                            RoleId = "c9998673-0fd7-4ead-ab18-b0ea8a22999c"
                        },
                        new
                        {
                            UserId = "d5d1c1bc-b50f-4835-998d-04fd98833154",
                            RoleId = "8453e6fc-6c42-470e-a602-f3263b60ac30"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("TagWidget", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("WidgetsId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "WidgetsId");

                    b.HasIndex("WidgetsId");

                    b.ToTable("TagWidget");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Assignment", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Widget", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Attendance", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.BatchBudget", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.ClassSchedule", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Widget", "Module")
                        .WithMany()
                        .HasForeignKey("WidgetId");

                    b.Navigation("Batch");

                    b.Navigation("Instructor");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.FinAccount", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Student", "Student")
                        .WithOne("FinAccount")
                        .HasForeignKey("AppTechnoSoft.Interns.Data.Models.FinAccount", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Instructor", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Student", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Batch", "Batch")
                        .WithMany("Students")
                        .HasForeignKey("BatchId");

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId");

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Team", "Team")
                        .WithMany("Students")
                        .HasForeignKey("TeamId");

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.TechProgram", "TechProgram")
                        .WithMany()
                        .HasForeignKey("TechProgramId");

                    b.Navigation("Batch");

                    b.Navigation("College");

                    b.Navigation("Team");

                    b.Navigation("TechProgram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.StudentAssignment", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Instructor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Team", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Batch", "Batch")
                        .WithMany("Teams")
                        .HasForeignKey("BatchId");

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("Batch");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("InstructorTag", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagWidget", b =>
                {
                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppTechnoSoft.Interns.Data.Models.Widget", null)
                        .WithMany()
                        .HasForeignKey("WidgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Batch", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Student", b =>
                {
                    b.Navigation("FinAccount");
                });

            modelBuilder.Entity("AppTechnoSoft.Interns.Data.Models.Team", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
